// <auto-generated />
using System;
using IDCOL.CBS.SystemAdmin.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace IDCOL.CBS.SystemAdmin.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SystemAdminDbContext))]
    partial class SystemAdminDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IDCOL.CBS.SystemAdmin.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("AUDIT_LOG_ENTRY_ID");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("ACTION_NAME");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ACTOR_USER_ID");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("CLOB")
                        .HasColumnName("DETAILS_JSON");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ENTITY_ID");

                    b.Property<string>("EntityType")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("ENTITY_TYPE");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("OCCURRED_AT_UTC");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("SYSAD_AUDIT_LOG_ENTRY", (string)null);
                });

            modelBuilder.Entity("IDCOL.CBS.SystemAdmin.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("PERMISSION_ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CODE");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRIPTION");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SYSAD_PERMISSION", (string)null);
                });

            modelBuilder.Entity("IDCOL.CBS.SystemAdmin.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ROLE_ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CODE");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT_UTC");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LAST_MODIFIED_AT_UTC");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("LAST_MODIFIED_BY");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SYSAD_ROLE", (string)null);
                });

            modelBuilder.Entity("IDCOL.CBS.SystemAdmin.Domain.Entities.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ROLE_ASSIGNMENT_ID");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ASSIGNED_AT_UTC");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ASSIGNED_BY");

                    b.Property<string>("FunctionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("FUNCTION_CODE");

                    b.Property<string>("IsChecker")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("IS_CHECKER");

                    b.Property<string>("IsMaker")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("IS_MAKER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "FunctionCode")
                        .IsUnique();

                    b.ToTable("SYSAD_ROLE_ASSIGNMENT", null, t =>
                        {
                            t.HasCheckConstraint("CK_ROLE_ASSIGNMENT_NOT_BOTH", "NOT (IS_MAKER = 'Y' AND IS_CHECKER = 'Y')");
                        });
                });

            modelBuilder.Entity("IDCOL.CBS.SystemAdmin.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("USER_ID");

                    b.Property<string>("BusinessUnitCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("BUSINESS_UNIT_CODE");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT_UTC");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DISPLAY_NAME");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("EMAIL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LAST_MODIFIED_AT_UTC");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("LAST_MODIFIED_BY");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("PASSWORD_HASH");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("SYSAD_USER", (string)null);
                });

            modelBuilder.Entity("SYSAD_ROLE_PERMISSION", b =>
                {
                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("PermissionsId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("SYSAD_ROLE_PERMISSION");
                });

            modelBuilder.Entity("SYSAD_USER_ROLE", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("RolesId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("SYSAD_USER_ROLE");
                });

            modelBuilder.Entity("IDCOL.CBS.SystemAdmin.Domain.Entities.RoleAssignment", b =>
                {
                    b.HasOne("IDCOL.CBS.SystemAdmin.Domain.Entities.User", null)
                        .WithMany("RoleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SYSAD_ROLE_PERMISSION", b =>
                {
                    b.HasOne("IDCOL.CBS.SystemAdmin.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IDCOL.CBS.SystemAdmin.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SYSAD_USER_ROLE", b =>
                {
                    b.HasOne("IDCOL.CBS.SystemAdmin.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IDCOL.CBS.SystemAdmin.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IDCOL.CBS.SystemAdmin.Domain.Entities.User", b =>
                {
                    b.Navigation("RoleAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
