<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-IDCOL.CBS.Worker-16e73a96-9387-428c-b2c1-90666e33c86f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\SystemAdmin\IDCOL.CBS.SystemAdmin.Infrastructure\IDCOL.CBS.SystemAdmin.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\SystemAdmin\IDCOL.CBS.SystemAdmin.Application\IDCOL.CBS.SystemAdmin.Application.csproj" />
  </ItemGroup>
</Project>
