<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\ProductConfig\IDCOL.CBS.ProductConfig.Domain\IDCOL.CBS.ProductConfig.Domain.csproj" />
    <ProjectReference Include="..\..\ProductConfig\IDCOL.CBS.ProductConfig.Application\IDCOL.CBS.ProductConfig.Application.csproj" />
    <ProjectReference Include="..\..\PartyKyc\IDCOL.CBS.PartyKyc.Domain\IDCOL.CBS.PartyKyc.Domain.csproj" />
    <ProjectReference Include="..\..\PartyKyc\IDCOL.CBS.PartyKyc.Application\IDCOL.CBS.PartyKyc.Application.csproj" />
    <ProjectReference Include="..\..\CreditSanction\IDCOL.CBS.CreditSanction.Domain\IDCOL.CBS.CreditSanction.Domain.csproj" />
    <ProjectReference Include="..\..\CreditSanction\IDCOL.CBS.CreditSanction.Application\IDCOL.CBS.CreditSanction.Application.csproj" />
    <ProjectReference Include="..\..\..\Shared\IDCOL.CBS.BuildingBlocks.Application\IDCOL.CBS.BuildingBlocks.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.2" />
    <PackageReference Include="Oracle.EntityFrameworkCore" Version="8.23.60" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
