import { CommonModule } from '@angular/common';
import { Component, OnInit, computed, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { AuthService } from '../../core/auth/auth.service';
import {
  AddFacilityVersionRequest, Facility, FacilityVersion, FacilityVersionEventType
} from '../../core/facilities/facility.models';
import { FacilityService } from '../../core/facilities/facility.service';
import { LifecycleService } from '../../core/lifecycle/lifecycle.service';
import { Sanction } from '../../core/lifecycle/lifecycle.models';
import { ScheduleParameters, ScheduleRow } from '../../core/repayment/repayment.models';
import { addMonthsToIso, isoToSerial, serialToIso } from '../../core/repayment/serial-date';

@Component({
  selector: 'app-facility-versions',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  templateUrl: './facility-versions.component.html'
})
export class FacilityVersionsComponent implements OnInit {
  sanctionId = '';
  readonly sanction = signal<Sanction | null>(null);
  readonly facilities = signal<Facility[]>([]);
  readonly selectedFacilityId = signal<string | null>(null);
  readonly selectedVersionId = signal<string | null>(null);
  readonly schedule = signal<ScheduleRow[]>([]);
  readonly editMode = signal(false);
  readonly showWizard = signal(false);
  readonly busy = signal(false);
  readonly errorMessage = signal<string | null>(null);

  readonly canModify = computed(() => (this.auth.currentUser()?.roleCodes ?? []).includes('CAD'));

  readonly eventTypes: FacilityVersionEventType[] =
    ['Reschedule', 'Restructure', 'RateChange', 'Prepayment', 'MoratoriumExtension'];

  wizard = {
    eventType: 'Reschedule' as FacilityVersionEventType,
    effectiveDate: new Date().toISOString().slice(0, 10),
    label: '',
    newRatePercent: 0,
    newTenorMonths: 0,
    newInstallments: 0,
    newPaymentFrequency: 4,
    newDayCountBasis: 360,
    newPrincipalType: 'Level Principal',
    capitalizedAmount: 0,
    waivedAmount: 0,
    overdueAmountRolledIn: 0,
    regulatoryReference: ''
  };

  readonly selectedFacility = computed(() =>
    this.facilities().find((f) => f.id === this.selectedFacilityId()) ?? null);

  readonly selectedVersion = computed(() =>
    this.selectedFacility()?.versions.find((v) => v.id === this.selectedVersionId()) ?? null);

  readonly totals = computed(() => {
    const rows = this.schedule();
    return {
      interest: rows.reduce((s, r) => s + r.interest, 0),
      principal: rows.reduce((s, r) => s + r.principal, 0)
    };
  });

  constructor(
    private readonly route: ActivatedRoute,
    private readonly facilityService: FacilityService,
    private readonly lifecycleService: LifecycleService,
    private readonly auth: AuthService
  ) {}

  ngOnInit(): void {
    this.sanctionId = this.route.snapshot.paramMap.get('sanctionId') ?? '';
    this.lifecycleService.listSanctions().subscribe((all) => {
      this.sanction.set(all.find((s) => s.id === this.sanctionId) ?? null);
    });
    this.reload();
  }

  reload(): void {
    this.facilityService.bySanction(this.sanctionId).subscribe({
      next: (facilities) => {
        this.facilities.set(facilities);
        if (facilities.length > 0) {
          this.selectFacility(facilities[0].id);
        }
      },
      error: () => this.errorMessage.set('Could not load facilities.')
    });
  }

  selectFacility(facilityId: string): void {
    this.selectedFacilityId.set(facilityId);
    const facility = this.facilities().find((f) => f.id === facilityId);
    const active = facility?.versions.find((v) => v.status === 'Active') ?? facility?.versions.at(-1);
    if (active) this.selectVersion(active.id);
  }

  selectVersion(versionId: string): void {
    this.selectedVersionId.set(versionId);
    this.editMode.set(false);
    const facilityId = this.selectedFacilityId();
    if (!facilityId) return;
    this.facilityService.getSchedule(facilityId, versionId).subscribe({
      next: (rows) => this.schedule.set(rows),
      error: () => this.errorMessage.set('Could not compute this version\'s schedule.')
    });
  }

  isoDate(serial: number): string {
    return serialToIso(serial);
  }

  /**
   * Builds the ORIGINAL facility straight from the signed sanction's already-captured terms.
   * Repayment dates are generated by the engine itself (gen_mode "auto"): the first installment
   * falls one payment-frequency step after the longer of the interest-grace / principal-moratorium
   * period, on the same day-of-month as the agreement date.
   */
  generateOriginal(): void {
    const s = this.sanction();
    if (!s) return;

    const graceMonths = Math.max(s.interestGracePeriodMonths, s.principalMoratoriumMonths);
    const stepMonths = Math.max(1, Math.round(12 / s.principalFrequency));
    const firstPaymentIso = addMonthsToIso(s.agreementDate, graceMonths + stepMonths);
    const agreementSerial = isoToSerial(s.agreementDate);

    const params: ScheduleParameters = {
      projectName: s.projectName,
      currency: s.loanCurrency,
      loanAmount: s.loanAmount,
      interestRate: s.initialInterestRatePercent / 100,
      dayCountBasis: s.dayCountBasis,
      numInstallments: s.noOfPrincipalRepayments,
      principalType: s.repaymentMethod,
      paymentFrequency: s.principalFrequency,
      interestGracePeriodEnd: s.interestGracePeriodMonths > 0
        ? isoToSerial(addMonthsToIso(s.agreementDate, s.interestGracePeriodMonths)) : null,
      principalGracePeriodEnd: s.principalMoratoriumMonths > 0
        ? isoToSerial(addMonthsToIso(s.agreementDate, s.principalMoratoriumMonths)) : null,
      interestCapitalized: false,
      interestCapitalizedUntil: null,
      openingBalanceIncludesPeriodDisbursements: true,
      disbursements: [{ dateSerial: agreementSerial, amount: s.loanAmount }],
      repaymentDates: [],
      interestRateChangeEvents: [],
      interestDayAdjustments: [],
      principalSchedulePercentages: null,
      principalScheduleAmounts: null,
      interestRatesByPeriod: null,
      interestPaymentAmounts: null,
      openingBalanceAmounts: null,
      closingBalanceAmounts: null,
      annuityRecalculateOnRateOrDisbursement: false,
      annuityUsePeriodRate: false,
      totalDebtServiceMode: null,
      totalDebtServiceIncludesCapitalizedInterest: false,
      genMode: 'auto',
      firstPayment: isoToSerial(firstPaymentIso),
      paymentDay: Number(s.agreementDate.split('-')[2]),
      bdRule: 'none',
      weekendFriSat: true,
      weekendSatSun: false,
      holidays: []
    };

    this.busy.set(true);
    this.errorMessage.set(null);
    this.facilityService.createOriginal({
      sanctionId: this.sanctionId,
      lenderCode: 'IDCOL',
      currency: s.loanCurrency,
      effectiveDate: s.agreementDate,
      parameters: params
    }).subscribe({
      next: () => { this.busy.set(false); this.reload(); },
      error: (e) => {
        this.busy.set(false);
        this.errorMessage.set(e?.error?.detail ?? e?.error?.title ?? 'Could not generate the original schedule.');
      }
    });
  }

  submitWizard(): void {
    const facility = this.selectedFacility();
    const current = this.selectedVersion();
    if (!facility || !current) return;

    const currentRows = this.schedule();
    const lastClose = currentRows.length > 0 ? currentRows[currentRows.length - 1].closingBal : current.parameters.loanAmount;
    const rolledForward = lastClose + this.wizard.capitalizedAmount + this.wizard.overdueAmountRolledIn;

    const newParams: ScheduleParameters = {
      ...current.parameters,
      loanAmount: rolledForward,
      interestRate: this.wizard.newRatePercent / 100,
      numInstallments: this.wizard.newInstallments,
      paymentFrequency: this.wizard.newPaymentFrequency,
      dayCountBasis: this.wizard.newDayCountBasis,
      principalType: this.wizard.newPrincipalType,
      disbursements: [{ dateSerial: isoToSerial(this.wizard.effectiveDate), amount: rolledForward }],
      repaymentDates: [],
      interestGracePeriodEnd: null,
      principalGracePeriodEnd: null,
      interestPaymentAmounts: null,
      openingBalanceAmounts: null,
      closingBalanceAmounts: null
    };

    const request: AddFacilityVersionRequest = {
      eventType: this.wizard.eventType,
      effectiveDate: this.wizard.effectiveDate,
      label: this.wizard.label || this.wizard.eventType,
      sourceFile: null,
      rateBeforePercent: (current.parameters.interestRate ?? 0) * 100,
      rateAfterPercent: this.wizard.newRatePercent,
      tenorMonthsBefore: this.wizard.newTenorMonths ? current.tenorMonthsAfter ?? null : null,
      tenorMonthsAfter: this.wizard.newTenorMonths || null,
      capitalizedAmount: this.wizard.capitalizedAmount,
      waivedAmount: this.wizard.waivedAmount,
      overdueAmountRolledIn: this.wizard.overdueAmountRolledIn,
      regulatoryReference: this.wizard.regulatoryReference || null,
      parameters: newParams
    };

    this.busy.set(true);
    this.errorMessage.set(null);
    this.facilityService.addVersion(facility.id, request).subscribe({
      next: () => {
        this.busy.set(false);
        this.showWizard.set(false);
        this.reload();
      },
      error: (e) => {
        this.busy.set(false);
        this.errorMessage.set(e?.error?.detail ?? e?.error?.title ?? 'Could not create the new version.');
      }
    });
  }

  /** Local editable copies, keyed by installment index, for the in-table override inputs. */
  editBuffer: Record<number, { interest: number; opening: number; closing: number }> = {};

  beginEditRow(row: ScheduleRow): void {
    this.editBuffer[row.idx] = { interest: row.cashInterest, opening: row.openingBal, closing: row.closingBal };
  }

  saveRowOverride(row: ScheduleRow): void {
    const facility = this.selectedFacilityId();
    const version = this.selectedVersionId();
    const edited = this.editBuffer[row.idx];
    if (!facility || !version || !edited) return;

    this.facilityService.applyOverride(facility, version, row.idx, {
      interestOverride: edited.interest,
      openingBalanceOverride: edited.opening,
      closingBalanceOverride: edited.closing
    }).subscribe({
      next: () => { delete this.editBuffer[row.idx]; this.selectVersion(version); },
      error: (e) => this.errorMessage.set(e?.error?.detail ?? 'Override failed.')
    });
  }

  badgeClass(eventType: string): string {
    return eventType === 'Original' ? 'signed' : 'pending';
  }
}
